---
- name: Send notify to Telegram
  community.general.telegram:
    token: '6060974585:AAFM95tyQjzo52CMHZQknzTM9teHk0_2OuY'
    api_args:
      chat_id: -900228251
      parse_mode: "markdown"
      text: "Source IP Address has been blocked - Reason: {{ reason }}"
      disable_web_page_preview: true
      disable_notification: true
  when: services == 'dvcqgdientaps'
- name: Send notify to Telegram
  community.general.telegram:
    token: '6060974585:AAFM95tyQjzo52CMHZQknzTM9teHk0_2OuY'
    api_args:
      chat_id: -900228251
      parse_mode: "markdown"
      text: "Source IP Address has been blocked - Reason: {{ reason }}"
      disable_web_page_preview: true
      disable_notification: true
  when: services == 'hanoinews'
- name: Send notify to Telegram
  community.general.telegram:
    token: '6060974585:AAFM95tyQjzo52CMHZQknzTM9teHk0_2OuY'
    api_args:
      chat_id: -900228251
      parse_mode: "markdown"
      text: "Source IP Address {{ source_address }} has been blocked - Reason: {{ reason }}"
      disable_web_page_preview: true
      disable_notification: true
  when: services == 'congthongtinchinhphu'
